### ISSUE TITLE
组件属性`noPreview`状态切换，页面的所有组件views全部丢失

### ISSUE THREAD

**Issue by LonelyFellas** [uiwjs/react-code-preview#235]
https://github.com/uiwjs/react-code-preview/assets/38754760/1b3ee2a3-559d-4c14-808a-b6693706cc1b

**Comment by jaywcjlove** [comment]
https://github.com/uiwjs/react-code-preview/blob/97e4c6cbd7e89d1e0d42fa3617a1a9244a25692d/src/useCodePreview.ts#L40-L52

上面示例是找到 `dom` 重新 `render`， 当你切换`示例预览`的时候，导致 `ReactDOMRoot` root 节点还是以前的，如下代码切换的时候 dom 节点被更新了

https://github.com/uiwjs/react-code-preview/blob/97e4c6cbd7e89d1e0d42fa3617a1a9244a25692d/src/index.tsx#L195-L216

@LonelyFellas

**Comment by jaywcjlove** [comment]
@LonelyFellas 有一个解决方法，对预览的展示隐藏通过 css 去控制节点就不会被移除
